export const ENDPOINTS = {
  AUTH_LOGIN: '/api/auth/login',
  AUTH_REQUEST_ACCESS: '/api/auth/request-access',
  AUTH_APPROVE: '/api/auth/approve-access',
  AUTH_REVOKE: '/api/auth/revoke-access',
  EVENTS: '/api/events',
  EVENT_BY_ID: (id: string) => `/api/events/${id}`,
  EVENT_RSVP: '/api/events/rsvp',
  USERS: '/api/users',
  USER_BY_ID: (id: string) => `/api/users/${id}`,
  USER_PROMOTE: '/api/users/promote',
  BIRTHDAYS_UPCOMING: '/api/birthdays/upcoming',
  BIRTHDAYS_GENERATE: '/api/birthdays/generate',
  NOTIFICATIONS: '/api/notifications',
  NOTIFICATIONS_SEND: '/api/notifications/send',
  ADMIN_DASHBOARD: '/api/admin/dashboard',
  ADMIN_CONTENT: '/api/admin/content',
  ADMIN_CREATE_ADMIN: '/api/admin/create-admin',
} as const
